"""Remove timeline column from sub_activities

Revision ID: 0f5775b0d0d2
Revises: dc7640ca2bd3
Create Date: 2026-01-20 20:31:20.013937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f5775b0d0d2'
down_revision = 'dc7640ca2bd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sub_activities', schema=None) as batch_op:
        batch_op.drop_column('timeline')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sub_activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timeline', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
