"""add_qualitative_stage_fields

Revision ID: 26d948b49487
Revises: 78eb30f6dcb3
Create Date: 2025-12-23 20:38:16.730736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26d948b49487'
down_revision = '78eb30f6dcb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indicators', sa.Column('qualitative_stage_year1', sa.String(), nullable=True))
    op.add_column('indicators', sa.Column('qualitative_stage_year2', sa.String(), nullable=True))
    op.add_column('indicators', sa.Column('qualitative_stage_year3', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('indicators', 'qualitative_stage_year3')
    op.drop_column('indicators', 'qualitative_stage_year2')
    op.drop_column('indicators', 'qualitative_stage_year1')
    # ### end Alembic commands ###
