"""add password_version to users

Revision ID: 310e8806477a
Revises: eb786a4b61a0
Create Date: 2026-04-27 17:13:45.818934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '310e8806477a'
down_revision = 'eb786a4b61a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_version', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_version')

    # ### end Alembic commands ###
