"""empty message

Revision ID: 45f5834c537a
Revises: 6e111a3bf9e2
Create Date: 2025-12-04 12:13:16.066021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45f5834c537a'
down_revision = '6e111a3bf9e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if table already exists (for cases where it was created manually)
    from sqlalchemy import inspect
    
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()
    
    if 'sub_activities' not in existing_tables:
        op.create_table('sub_activities',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('activity_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('responsible', sa.String(), nullable=True),
        sa.Column('timeline', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    else:
        # Table exists - check if status column exists, add it if missing
        existing_columns = [col['name'] for col in inspector.get_columns('sub_activities')]
        if 'status' not in existing_columns:
            op.add_column('sub_activities', sa.Column('status', sa.String(), nullable=True, server_default='pending'))
            op.execute("UPDATE sub_activities SET status = 'pending' WHERE status IS NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if table exists before dropping
    from sqlalchemy import inspect
    
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()
    
    if 'sub_activities' in existing_tables:
        op.drop_table('sub_activities')
    # ### end Alembic commands ###
