"""add status column to challenges

Revision ID: 6e111a3bf9e2
Revises: 9cad6b15c766
Create Date: 2025-12-03 17:50:57.310986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e111a3bf9e2'
down_revision = '9cad6b15c766'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add status column with default value
    # First add as nullable, then set defaults, then make it NOT NULL
    op.add_column('challenges', sa.Column('status', sa.String(), nullable=True))
    # Set default for existing rows
    op.execute("UPDATE challenges SET status = 'pending' WHERE status IS NULL")
    # Now make it NOT NULL
    op.alter_column('challenges', 'status', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challenges', 'status')
    # ### end Alembic commands ###
