"""empty message

Revision ID: 78eb30f6dcb3
Revises: 0968a2787c01
Create Date: 2025-12-23 18:55:48.566764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78eb30f6dcb3'
down_revision = '0968a2787c01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Foreign key operations removed - the foreign key already exists from add_indicators_table migration
    # Alembic incorrectly detected it as changed, but no action is needed.
    
    # Check if status column already exists before adding it
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('sub_activities')]
    
    if 'status' not in columns:
        with op.batch_alter_table('sub_activities', schema=None) as batch_op:
            batch_op.add_column(sa.Column('status', sa.String(), nullable=False, server_default='pending'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sub_activities', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
