"""add indicators table

Revision ID: add_indicators
Revises: add_user_activities
Create Date: 2025-12-12 23:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "add_indicators"
down_revision = "add_user_activities"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "indicators",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("activity_id", sa.Integer(), nullable=False),
        sa.Column("activity_code", sa.String(), nullable=True),
        sa.Column("fundholder_implementing_entity", sa.String(), nullable=True),
        sa.Column("key_project_activity", sa.Text(), nullable=True),
        sa.Column("new_proposed_indicator", sa.Text(), nullable=True),
        sa.Column("indicator_type", sa.String(), nullable=True),
        sa.Column("naphs", sa.String(), nullable=True),
        sa.Column("indicator_definition", sa.Text(), nullable=True),
        sa.Column("data_source", sa.String(), nullable=True),
        sa.Column("baseline_proposal_year", sa.String(), nullable=True),
        sa.Column("target_year1", sa.String(), nullable=True),
        sa.Column("target_year2", sa.String(), nullable=True),
        sa.Column("target_year3", sa.String(), nullable=True),
        sa.Column("submitted", sa.String(), nullable=True),
        sa.Column("comments", sa.Text(), nullable=True),
        sa.Column("portal_edited", sa.String(), nullable=True),
        sa.Column("comment_addressed", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["activity_id"], ["activities.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_indicators_activity_id"),
        "indicators",
        ["activity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_indicators_activity_code"),
        "indicators",
        ["activity_code"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_indicators_activity_code"), table_name="indicators")
    op.drop_index(op.f("ix_indicators_activity_id"), table_name="indicators")
    op.drop_table("indicators")
    # ### end Alembic commands ###


