"""add sub_activities table

Revision ID: d4b0ebf42fa1
Revises: 45f5834c537a
Create Date: 2025-12-04 12:22:48.440873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4b0ebf42fa1'
down_revision = '45f5834c537a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: sqlite_sequence is a system table managed by SQLite and cannot be dropped
    # Skip dropping it - this migration was likely auto-generated incorrectly
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: sqlite_sequence is a system table managed by SQLite
    # No need to recreate it
    pass
    # ### end Alembic commands ###
