"""empty message

Revision ID: d62b14b23d88
Revises: 26d948b49487
Create Date: 2025-12-23 20:42:55.435159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd62b14b23d88'
down_revision = '26d948b49487'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Foreign key already exists, no changes needed
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Foreign key already exists, no changes needed
    pass
    # ### end Alembic commands ###
