"""budget columns added on sub-activity

Revision ID: eb786a4b61a0
Revises: add_activity_reports
Create Date: 2026-02-03 13:34:43.661155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb786a4b61a0'
down_revision = 'add_activity_reports'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_reports', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_activity_reports_activity_id'), type_='unique')

    with op.batch_alter_table('indicators', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_indicators_activity_id'), type_='unique')
        batch_op.create_index(batch_op.f('ix_indicators_activity_id'), ['activity_id'], unique=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'activities', ['activity_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indicators', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'activities', ['activity_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_indicators_activity_id'))
        batch_op.create_unique_constraint(batch_op.f('uq_indicators_activity_id'), ['activity_id'])

    with op.batch_alter_table('activity_reports', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_activity_reports_activity_id'), ['activity_id'])

    # ### end Alembic commands ###
